# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/VIVADO_workspace/image_rotate/image_rotate.srcs/sources_1/ip/bram_out/bram_out.xci
# IP: The module: 'bram_out' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VIVADO_workspace/image_rotate/image_rotate.gen/sources_1/ip/bram_out_1/bram_out_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_out'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/VIVADO_workspace/image_rotate/image_rotate.srcs/sources_1/ip/bram_out/bram_out.xci
# IP: The module: 'bram_out' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VIVADO_workspace/image_rotate/image_rotate.gen/sources_1/ip/bram_out_1/bram_out_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
