# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/VIVADO WORKSPACE/testing/image_rotate/image_rotate.srcs/sources_1/ip/bram_in/bram_in.xci
# IP: The module: 'bram_in' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/VIVADO WORKSPACE/testing/image_rotate/image_rotate.gen/sources_1/ip/bram_in_3/bram_in_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_in'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: F:/VIVADO WORKSPACE/testing/image_rotate/image_rotate.srcs/sources_1/ip/bram_in/bram_in.xci
# IP: The module: 'bram_in' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/VIVADO WORKSPACE/testing/image_rotate/image_rotate.gen/sources_1/ip/bram_in_3/bram_in_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_in'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
